name: to_do_app
description: "A To-Do-List App."

publish_to: 'none' 

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
